NL = chr(10)
L = []

L.append('"use client";')
L.append('')
L.append('import { useState } from "react";')
L.append('')
L.append('const APP_URL =')
L.append('  process.env.NEXT_PUBLIC_APP_URL ||')
L.append('  (typeof window !== "undefined" ? window.location.origin : "");')
L.append('')

L.append('const CONSOLE_CODE = String.raw`(function(){')
L.append('  var APP_URL = "${APP_URL}";')
L.append('  function fallback() {')
L.append('    var v = localStorage.getItem("persist:root");')
L.append('    if (!v) { alert("persist:root tidak ditemukan."); return; }')
L.append('    location.href = APP_URL + "/#t=" + encodeURIComponent(v);')
L.append('  }')
L.append('  var root = localStorage.getItem("persist:root");')
L.append('  var token = null;')
L.append('  if (root) {')
L.append('    try {')
L.append('      var parsed = JSON.parse(root);')
L.append('      var userStr = parsed.user;')
L.append('      if (typeof userStr === "string") {')
L.append('        var user = JSON.parse(userStr);')
L.append('        if (user && user.access_token) { token = user.access_token; }')
L.append('      }')
L.append('    } catch(e) {}')
L.append('  }')
L.append('  if (!token) { fallback(); return; }')
L.append('  fetch("https://api.fotoyu.com/gs/v1/carts/preview", {')
L.append('    method: "POST",')
L.append('    headers: {')
L.append('      "Content-Type": "application/json",')
L.append('      "Accept": "application/json, text/plain, */*",')
L.append('      "Authorization": "Bearer " + token')
L.append('    },')
L.append('    body: JSON.stringify({page:1,limit:100,selected_products:[]})')
L.append('  })')
L.append('  .then(function(r){ return r.json().then(function(j){ return {ok:r.ok,json:j}; }); })')
L.append('  .then(function(o){')
L.append('    if (o.ok && o.json && o.json.result && Array.isArray(o.json.result.data)) {')
L.append('      location.href = APP_URL + "/#cart=" + encodeURIComponent(JSON.stringify(o.json));')
L.append('    } else { fallback(); }')
L.append('  })')
L.append('  .catch(function(){ fallback(); });')
L.append('})();`;')
L.append('')
L.append('// NEWLINE PLACEHOLDER')

out = r"D:\PYTHON PROJECT\fotoyu downloader\web\components\BookmarkletSection.tsx"
with open(out, "w", encoding="utf-8") as f:
    f.write(NL.join(L))
print("part1 done")
